// interface.ts

export interface PAIS {
    codpais: string;
    descpais: string;
    codpais_eq?: number; // Opcional, ya que no todos los países tienen este valor
  }

  export interface Estado {
    CODPAIS: string;
    CODESTADO: string;
    DESCESTADO: string;
    ZONAGEOGRAFICA: string | null;
    ZONAAUTO: string | null;
    ZONABAREMO: string | null;
    CODESTADO_EQ: string | number | null;
}


export interface Ciudad {
  CODCIUDAD: string;
  CODCIUDAD_EQ: string;
  CODESTADO:string;
  CODPAIS:string;
  DESCCIUDAD:string;
}

export interface Municipio {
  CODCIUDAD: string;
  CODESTADO: string,
  CODMUNICIPIO: string;
  CODPAIS: string;
  DESCMUNICIPIO: string;
  CODMUNICIPIO_EQ: string;
}

export interface Parroquia {
  CODPARROQUIA:string;
  DESCPARROQUIA: string;
}

 export const paises: PAIS[] = [
  { codpais: '001', descpais: 'REPÚBLICA BOLIVARIANA DE VENEZUELA', codpais_eq: 229 },
 ];
  

 export interface Marca  {
  CODMARCA:string;
  DESCMARCA:string;
 }

 export interface Modelo {
  CODMARCA: string;
  CODMODELO: string;
  DESCMODELO: string;
 }

 export interface Version {
  CODMARCA:string;
  CODMODELO:string;
  CODVERSION: string;
  DESCVERSION:string;
  TIPOVEH: string;
 }

export const estados: Estado[] = [
    { CODPAIS: '001', CODESTADO: '002', DESCESTADO: 'AMAZONAS', ZONAGEOGRAFICA: '03', ZONAAUTO: '02', ZONABAREMO: '03', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '003', DESCESTADO: 'ANZOÁTEGUI', ZONAGEOGRAFICA: '03', ZONAAUTO: '02', ZONABAREMO: '03', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '004', DESCESTADO: 'APURE', ZONAGEOGRAFICA: '04', ZONAAUTO: '02', ZONABAREMO: '04', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '005', DESCESTADO: 'ARAGUA', ZONAGEOGRAFICA: '04', ZONAAUTO: '03', ZONABAREMO: '04', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '006', DESCESTADO: 'BARINAS', ZONAGEOGRAFICA: '05', ZONAAUTO: '02', ZONABAREMO: '05', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '007', DESCESTADO: 'BOLÍVAR', ZONAGEOGRAFICA: '03', ZONAAUTO: '02', ZONABAREMO: '03', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '008', DESCESTADO: 'CARABOBO', ZONAGEOGRAFICA: '04', ZONAAUTO: '03', ZONABAREMO: '04', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '009', DESCESTADO: 'COJEDES', ZONAGEOGRAFICA: '05', ZONAAUTO: '02', ZONABAREMO: '05', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '010', DESCESTADO: 'DELTA AMACURO', ZONAGEOGRAFICA: '03', ZONAAUTO: '02', ZONABAREMO: '03', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '001', DESCESTADO: 'DISTRITO CAPITAL', ZONAGEOGRAFICA: '01', ZONAAUTO: '04', ZONABAREMO: '01', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '011', DESCESTADO: 'FALCÓN', ZONAGEOGRAFICA: '02', ZONAAUTO: '02', ZONABAREMO: '02', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '012', DESCESTADO: 'GUÁRICO', ZONAGEOGRAFICA: '04', ZONAAUTO: '02', ZONABAREMO: '04', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '013', DESCESTADO: 'LARA', ZONAGEOGRAFICA: '05', ZONAAUTO: '02', ZONABAREMO: '05', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '015', DESCESTADO: 'MIRANDA', ZONAGEOGRAFICA: '01', ZONAAUTO: '04', ZONABAREMO: '01', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '016', DESCESTADO: 'MONAGAS', ZONAGEOGRAFICA: '03', ZONAAUTO: '02', ZONABAREMO: '03', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '014', DESCESTADO: 'MERIDA', ZONAGEOGRAFICA: '06', ZONAAUTO: '02', ZONABAREMO: '06', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '017', DESCESTADO: 'NUEVA ESPARTA', ZONAGEOGRAFICA: '03', ZONAAUTO: '02', ZONABAREMO: '03', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '999', DESCESTADO: 'POR CONVERSIÓN', ZONAGEOGRAFICA: null, ZONAAUTO: null, ZONABAREMO: null, CODESTADO_EQ: 999 },
    { CODPAIS: '001', CODESTADO: '018', DESCESTADO: 'PORTUGUESA', ZONAGEOGRAFICA: '05', ZONAAUTO: '02', ZONABAREMO: '05', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '019', DESCESTADO: 'SUCRE', ZONAGEOGRAFICA: '03', ZONAAUTO: '02', ZONABAREMO: '03', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '021', DESCESTADO: 'TRUJILLO', ZONAGEOGRAFICA: '06', ZONAAUTO: '02', ZONABAREMO: '06', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '020', DESCESTADO: 'TACHIRA', ZONAGEOGRAFICA: '06', ZONAAUTO: '02', ZONABAREMO: '06', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '024', DESCESTADO: 'VARGAS', ZONAGEOGRAFICA: '01', ZONAAUTO: '02', ZONABAREMO: '01', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '022', DESCESTADO: 'YARACUY', ZONAGEOGRAFICA: '04', ZONAAUTO: '02', ZONABAREMO: '04', CODESTADO_EQ: null },
    { CODPAIS: '001', CODESTADO: '023', DESCESTADO: 'ZULIA', ZONAGEOGRAFICA: '02', ZONAAUTO: '01', ZONABAREMO: '02', CODESTADO_EQ: null }
];
